application: glabs20-sputnik
version: 1
runtime: python
api_version: 1

default_expiration: "1h"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /images
  static_dir: static/images
  expiration: "7d"

- url: /static
  static_dir: static
  expiration: "1h"

- url: /.*
  script: sputnik.py
