application: sputnik
version: 2
runtime: python
api_version: 1

default_expiration: "1h"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /images
  static_dir: static/images
  expiration: "7d"

- url: /static/goog/
  static_dir: static/goog
  expiration: "1d"

- url: /static
  static_dir: static
  expiration: "1s"

- url: /.*
  script: sputnik.py
